[build-system]
requires = ["release-gitter[builder]"]
build-backend = "pseudo_builder"

[tool.release-gitter]
git-url = "https://github.com/hadolint/hadolint"
format = "hadolint-{system}-{arch}"
exec = "mv {} hadolint && chmod +x hadolint"
